spring:
  datasource:
    url: ENC(w8JYlfb55/e2xRgnXr1I80CiyxyYPRdteF6lVTQH1Jo9yrcr5LzhqQ==)
    driver-class-name: org.h2.Driver
    username: ENC(uzYY3fWzGX4VSvJcNa7eEw==)
    password:
  jpa:
    hibernate:
      ddl-auto: update    # 테이블 자동 생성 및 업데이트
    show-sql: true        # 실행된 SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true       # H2 웹 콘솔 활성화
      path: /h2-console   # H2 콘솔 경로
  sql:
    init:
      mode: always        # schema.sql, data.sql 실행

json:
  location: "F:/json"