spring:
  datasource:
    url: ENC(dsadqJoxtVwMf+QKBKHf3j2bPTBbDZ0QfHp8F6iRKilQ81gtzsBIqbjnf2/sHWQcfkP/BxnvlpI=)
    driver-class-name: org.postgresql.Driver
    username: ENC(LWJs2AgSdy6pNy8mbrdzp2E77F9RAb3M)
    password: ENC(I+a5CrSrcAbw2eN3G0y4zdYyy0BxSeXh)
  jpa:
    hibernate:
      ddl-auto: validate  # 엔티티와 테이블 스키마 검증
    show-sql: true        # 실행된 SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never         # schema.sql, data.sql 실행

json:
  location: "/home/data/json"

server:
  shutdown: graceful