spring:
  datasource:
    url: ENC(Ni3F09wR/iWNU9PgEpwney5cgttkdfBaP28Busgz4ew=)
    driver-class-name: org.h2.Driver
    username: ENC(yDJEeKSG9bq9ekHK1G32JQ==)
    password:
  jpa:
    hibernate:
      ddl-auto: update    # 테이블 자동 생성 및 업데이트
    show-sql: true        # 실행된 SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true       # H2 웹 콘솔 활성화
      path: /h2-console   # H2 콘솔 경로
  sql:
    init:
      mode: always        # schema.sql, data.sql 실행

json:
  location: "F:/json"