spring:
  datasource:
    url: jdbc:h2:mem:meeting
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update  # 테이블 자동 생성 및 업데이트
    show-sql: true       # 실행된 SQL 쿼리 출력
  h2:
    console:
      enabled: true       # H2 웹 콘솔 활성화
      path: /h2-console   # H2 콘솔 경로