spring:
  datasource:
    url: ENC(fAbwXDJL4DUiGTv8Dm8tsUv0z1Djq2SwowH9vHgGw+AX1MgBsBn+Fbag/XshRRwoKdjzTAw+tIs=)
    driver-class-name: org.postgresql.Driver
    username: ENC(Up5MNBTdfUYu+K9+KrmaoUgG7jtIWNTG)
    password: ENC(1FZE2jBk82pvvUJA5HaZiFxBB95SiVxj)
  jpa:
    hibernate:
      ddl-auto: update    # 테이블 자동 생성 및 업데이트
    show-sql: true        # 실행된 SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never         # schema.sql, data.sql 실행

json:
  location: "/home/data/json"