spring:
  profiles:
    active: dev  # dev 환경
  config:
    import: jasypt.yml    # jasypt.yml
  servlet:
    multipart:
      max-file-size: 10MB     # 첨부파일 하나 최대 사이즈
      max-request-size: 10MB  # 첨부파일 전체 최대 사이즈

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE