spring:
  profiles:
    active: dev  # dev 환경

---
# test 환경

spring:
  datasource:
    url: ENC(w8JYlfb55/e2xRgnXr1I80CiyxyYPRdteF6lVTQH1Jo9yrcr5LzhqQ==)
    driver-class-name: org.h2.Driver
    username: ENC(uzYY3fWzGX4VSvJcNa7eEw==)
    password:
  jpa:
    hibernate:
      ddl-auto: update    # 테이블 자동 생성 및 업데이트
    show-sql: true        # 실행된 SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true       # H2 웹 콘솔 활성화
      path: /h2-console   # H2 콘솔 경로
  config:
    import: jasypt.yml    # jasypt.yml
  sql:
    init:
      mode: always        # schema.sql, data.sql 실행
  servlet:
    multipart:
      max-file-size: 10MB     # 첨부파일 하나 최대 사이즈
      max-request-size: 10MB  # 첨부파일 전체 최대 사이즈

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE

json:
  location: "F:/json"

---
# dev 환경

spring:
  datasource:
    url: ENC(fAbwXDJL4DUiGTv8Dm8tsUv0z1Djq2SwowH9vHgGw+AX1MgBsBn+Fbag/XshRRwoKdjzTAw+tIs=)
    driver-class-name: org.postgresql.Driver
    username: ENC(Up5MNBTdfUYu+K9+KrmaoUgG7jtIWNTG)
    password: ENC(1FZE2jBk82pvvUJA5HaZiFxBB95SiVxj)
  jpa:
    hibernate:
      ddl-auto: update    # 테이블 자동 생성 및 업데이트
    show-sql: true        # 실행된 SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true
  config:
    import: jasypt.yml    # jasypt.yml
  sql:
    init:
      mode: never         # schema.sql, data.sql 실행
  servlet:
    multipart:
      max-file-size: 10MB     # 첨부파일 하나 최대 사이즈
      max-request-size: 10MB  # 첨부파일 전체 최대 사이즈

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE

json:
  location: "/home/data/json"