spring:
  datasource:
    url: ENC(Nj4dh6gAPszIPYFaVoeIpFNJ9L+ECKFTXUM7P1LHuSyhcWAvNBgEG0Tci3R7R9ckB6TwjhWJubI=)
    driver-class-name: org.postgresql.Driver
    username: ENC(X46EQQ54W2YdCqvNkCTtGQlTypvtSfRO)
    password: ENC(JITZQMy9cPlyWnOxX8N11KkvP+wRrtb+)
  jpa:
    hibernate:
      ddl-auto: update    # 테이블 자동 생성 및 업데이트
    show-sql: true        # 실행된 SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never         # schema.sql, data.sql 실행

json:
  location: "/home/data/json"