CREATE TABLE MEETING (
     MEETING_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
     MEETING_DATE TIMESTAMP,
     MEETING_PLACE VARCHAR(50)
);

CREATE TABLE CONTENT (
     CONTENT_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
     CONTENT_NAME VARCHAR(100),
     CONTENT_CREATOR VARCHAR(100),
     CONTENT_RECOMMENDER VARCHAR(100),
     MEETING_SEQ BIGINT,
     FOREIGN KEY (MEETING_SEQ) REFERENCES MEETING(MEETING_SEQ)
);

CREATE TABLE MEMBER (
     MEMBER_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
     MEMBER_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE MEETING_MEMBER (
    MEETING_MEMBER_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    IS_ATTENDANCE BOOLEAN DEFAULT FALSE,
    MEETING_SEQ BIGINT,
    MEMBER_SEQ BIGINT,
    FOREIGN KEY (MEETING_SEQ) REFERENCES MEETING(MEETING_SEQ),
    FOREIGN KEY (MEMBER_SEQ) REFERENCES MEMBER(MEMBER_SEQ)
);